# Generated by Django 5.0.14 on 2026-03-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
