"""Document serializers."""
from rest_framework import serializers
from .models import Document


class DocumentSerializer(serializers.ModelSerializer):
    class Meta:
        #this connect serializerr to the document model and specify the fields to be serialized
        model = Document
        fields = ('id', 'file_url', 'uploaded_at', 'parsed')
        #can't be modified or posted by the user, only for read onlys, so we set read_only_fields to fields
        read_only_fields = fields

''' The below serializeer is not modelserialiser 
Because this is not directly saving to database.
It is used for:
Validating upload request data.
So we use serializers.Serializer instead of serializers.ModelSerializer. '''

'''A temporary permission generated by your backend that allows the 
frontend to upload a file directly  to cloud storage without passing through your server.'''
class PresignedUploadRequestSerializer(serializers.Serializer):
    #client must send string filename (resume.pdf)
    filename = serializers.CharField(max_length=255)
    # this tells the file content type which mean this pdf is documnet file not image or video
    # this is important for cloud storage to know how to handle the file
    content_type = serializers.CharField(default='application/pdf', max_length=100)
