# Generated by Django 5.0.14 on 2026-02-22 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='s3_key',
        ),
    ]
