# Generated by Django 5.0.14 on 2026-03-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_s3_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='recommended_roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
