# Generated by Django 5.0.14 on 2026-02-16 05:37

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=384)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='roles.role')),
            ],
        ),
        migrations.CreateModel(
            name='SkillEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=384)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='skills.skill')),
            ],
        ),
    ]
